services:
  - type: web
    name: wcursor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
